package com.ironhack.IronBooking.dto.review;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.Data;


@Data
public class ReviewRequestDTO {

    @Min(1)
    @Max(5)
    @NotNull
    private Integer rating;

    private String comment;

    // Usually we only pass the IDs from other objects
    @NotNull
    private Long userId;

    @NotNull
    private Long placeId;

    // Date not added since it will be automatically generated by the system, thanks to @CreationTimeStamp

}
